package com.edu.carrito.web.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CategoriaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaAllPropertiesEquals(Categoria expected, Categoria actual) {
        assertCategoriaAutoGeneratedPropertiesEquals(expected, actual);
        assertCategoriaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaAllUpdatablePropertiesEquals(Categoria expected, Categoria actual) {
        assertCategoriaUpdatableFieldsEquals(expected, actual);
        assertCategoriaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaAutoGeneratedPropertiesEquals(Categoria expected, Categoria actual) {
        assertThat(expected)
            .as("Verify Categoria auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaUpdatableFieldsEquals(Categoria expected, Categoria actual) {
        assertThat(expected)
            .as("Verify Categoria relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaUpdatableRelationshipsEquals(Categoria expected, Categoria actual) {
        // empty method
    }
}
